pipeline {
    agent any

    tools {
        maven 'maven-3'
        jdk 'jdk-21'
    }

    environment {
        REGISTRY = 'apexshieldacrdev.azurecr.io'
        IMAGE_NAME = 'spring-petclinic'
        ACR_CREDENTIALS = credentials('acr-credentials') // Pulls username and password from Jenkins store
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build & Package') {
            steps {
                dir('spring-petclinic') {
                    sh './mvnw clean package -DskipTests'
                }
            }
        }

        stage('Docker Build & Push') {
            steps {
                script {
                    // Login to ACR using standard docker CLI
                    sh "echo ${ACR_CREDENTIALS_PSW} | docker login ${REGISTRY} -u ${ACR_CREDENTIALS_USR} --password-stdin"
                    
                    // Build image using pre-built target jar
                    sh "docker build -t ${REGISTRY}/${IMAGE_NAME}:${BUILD_NUMBER} -t ${REGISTRY}/${IMAGE_NAME}:latest ./spring-petclinic"
                    
                    // Push images
                    sh "docker push ${REGISTRY}/${IMAGE_NAME}:${BUILD_NUMBER}"
                    sh "docker push ${REGISTRY}/${IMAGE_NAME}:latest"
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                script {
                    sh "sed -i 's/BUILD_NUMBER/${BUILD_NUMBER}/g' k8s/petclinic.yml"
                    sh "kubectl apply -f k8s/petclinic.yml"
                }
            }
        }
    }

    post {
        always {
            // Logout of ACR for security
            sh "docker logout ${REGISTRY} || true"
            cleanWs()
        }
    }
}