pipeline {
    agent any

    tools {
        maven 'maven-3'
    }

    environment {
        // --- AZURE & RESOURCE CONFIGURATION ---
        ACR_NAME          = 'apexshieldacrdev'                      
        ACR_SERVER        = 'apexshieldacrdev.azurecr.io'           
        IMAGE_NAME        = 'spring-petclinic'                      
        IMAGE_TAG         = "${BUILD_NUMBER}"                       
        RESOURCE_GROUP    = 'rg-apexshield-dev'                     
        AKS_CLUSTER_NAME  = 'aks-apexshield-dev'                    
        AZURE_CRED_ID     = 'azure-sp-credentials'                  
        SONAR_SERVER_NAME = 'sonar-server'                         
    }

    stages {
        stage('1. Checkout Code') {
            steps {
                git branch: 'main', url: 'https://github.com/praveenbhise07-art/spring-pet-clinic.git'
            }
        }

        stage('2. Build & Test with Maven') {
            steps {
                dir('spring-petclinic') {
                    sh 'mvn clean package -DskipTests=false'
                }
            }
        }

        stage('3. SonarQube Code Analysis') {
            steps {
                dir('spring-petclinic') {
                    script {
                        withSonarQubeEnv("${SONAR_SERVER_NAME}") {
                            sh 'mvn sonar:sonar'
                        }
                    }
                }
            }
        }

        stage('4. Docker Build') {
            steps {
                dir('spring-petclinic') {
                    sh "docker build -t ${ACR_SERVER}/${IMAGE_NAME}:${IMAGE_TAG} ."
                    sh "docker tag ${ACR_SERVER}/${IMAGE_NAME}:${IMAGE_TAG} ${ACR_SERVER}/${IMAGE_NAME}:latest"
                }
            }
        }

        stage('5. Trivy Security Vulnerability Scan') {
            steps {
                sh "trivy image --severity HIGH,CRITICAL ${ACR_SERVER}/${IMAGE_NAME}:${IMAGE_TAG}"
            }
        }

        stage('6. Login to Azure & ACR') {
            steps {
                withCredentials([azureServicePrincipal(
                    credentialsId: "${AZURE_CRED_ID}",
                    subscriptionIdVariable: 'AZURE_SUBSCRIPTION_ID',
                    clientIdVariable: 'AZURE_CLIENT_ID',
                    clientSecretVariable: 'AZURE_CLIENT_SECRET',
                    tenantIdVariable: 'AZURE_TENANT_ID'
                )]) {
                    sh "az login --service-principal -u \$AZURE_CLIENT_ID -p \$AZURE_CLIENT_SECRET --tenant \$AZURE_TENANT_ID"
                    sh "az acr login --name ${ACR_NAME}"
                }
            }
        }

        stage('7. Push Docker Image to ACR') {
            steps {
                sh "docker push ${ACR_SERVER}/${IMAGE_NAME}:${IMAGE_TAG}"
                sh "docker push ${ACR_SERVER}/${IMAGE_NAME}:latest"
            }
        }

        stage('8. Deploy to AKS via Helm') {
            steps {
                dir('spring-petclinic') {
                    withCredentials([azureServicePrincipal(
                        credentialsId: "${AZURE_CRED_ID}",
                        subscriptionIdVariable: 'AZURE_SUBSCRIPTION_ID',
                        clientIdVariable: 'AZURE_CLIENT_ID',
                        clientSecretVariable: 'AZURE_CLIENT_SECRET',
                        tenantIdVariable: 'AZURE_TENANT_ID'
                    )]) {
                        sh "az aks get-credentials --resource-group ${RESOURCE_GROUP} --name ${AKS_CLUSTER_NAME} --overwrite-existing"
                        
                        sh """
                            helm upgrade --install spring-petclinic ./helm \
                              --namespace dev \
                              --create-namespace \
                              --set image.repository=${ACR_SERVER}/${IMAGE_NAME} \
                              --set image.tag=${IMAGE_TAG}
                        """
                    }
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
        success {
            echo 'Pipeline completed successfully!'
        }
        failure {
            echo 'Pipeline failed. Check logs for details.'
        }
    }
}