pipeline {
    agent any

    tools {
        maven 'maven-3'
        jdk 'jdk-21'
    }

    environment {
        ACR_NAME   = 'apexshieldacrdev.azurecr.io'
        IMAGE_NAME = 'spring-petclinic'
        GIT_REPO   = 'https://github.com/praveenbhise07-art/spring-pet-clinic.git'
        GIT_BRANCH = 'feature/v2.0-release'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: "${env.GIT_BRANCH}", url: "${env.GIT_REPO}"
            }
        }

        stage('Build Application') {
            steps {
                dir('spring-petclinic-local') {
                    sh 'rm -rf target/'
                    sh 'chmod +x mvnw'
                    sh './mvnw clean package -DskipTests'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('spring-petclinic-local') {
                    sh "docker build --no-cache -t ${env.ACR_NAME}/${env.IMAGE_NAME}:${BUILD_NUMBER} -t ${env.ACR_NAME}/${env.IMAGE_NAME}:latest -f Dockerfile ."
                }
            }
        }

        stage('Push Image to ACR') {
            steps {
                withCredentials([azureServicePrincipal('azure-sp-credentials')]) {
                    sh "echo \${AZURE_CLIENT_SECRET} | docker login ${env.ACR_NAME} -u \${AZURE_CLIENT_ID} --password-stdin"
                    sh "docker push ${env.ACR_NAME}/${env.IMAGE_NAME}:${BUILD_NUMBER}"
                    sh "docker push ${env.ACR_NAME}/${env.IMAGE_NAME}:latest"
                }
            }
        }

        stage('Deploy to AKS') {
            steps {
                sh "kubectl set image deployment/petclinic petclinic=${env.ACR_NAME}/${env.IMAGE_NAME}:${BUILD_NUMBER}"
                sh "kubectl patch deployment petclinic -p '{\"spec\":{\"template\":{\"spec\":{\"containers\":[{\"name\":\"petclinic\",\"imagePullPolicy\":\"Always\"}]}}}}'"
                sh "kubectl rollout restart deployment/petclinic"
                sh "kubectl rollout status deployment/petclinic"
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}